# CQ3
# Where are cultural objects connected to thematic path X usually kept?  
# Dove sono solitamente conservati gli oggetti culturali connessi al percorso tematico X?  

# P.S. Replace the ThematicPathTitle to be searched in row 29, column 21.

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT ?PlaceName ?CulturalResourceTitle ?ThematicPathTitle
WHERE{  
   {  
    ?ThematicPath ctp:hasPart ?CulturalResource.  
  }  
  UNION  
  {  
    ?ThematicPath ctp:hasSlot ?OrderedListSlot.  
    ?OrderedListSlot ctp:hasItem ?CulturalResource.  
  }  
  ?CulturalResource ctp:isPreservedBy ?RelationToAgent.  
  ?RelationToAgent ctp:hasRole ?Role.  
  FILTER(?Role = <http://vocab.getty.edu/aat/300160390>)
  ?RelationToAgent ctp:involves ?Agent.  
  ?Agent ctp:hasPlace ?Place.  
  Optional{?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  Optional{?CulturalResource ctp:hasTitle ?CulturalResourceTitle}.  
  Optional{?Place ctp:hasTitle ?PlaceName}. 
  Optional{?Agent ctp:hasName ?AgentName}. 
  #?ThematicPath ctp:hasTitle ?p.  
  #FILTER(REGEX(?p, "InsertThematicPathTitleHere", "i")).  
}  

LIMIT 100  
