# CQ1
# What is a Thematic Paths?  
# Che cosa è un percorso tematico?  

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT ?Definition  
WHERE{  
  ctp:ThematicPath rdfs:comment ?Definition.  
  #FILTER(LANG(?Definition) ="en").  
}  
LIMIT 10  