# CQ10
# Which thematic paths have been created and by who?  
# Quali percorsi tematici sono stati realizzati e da quale agente?  

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
SELECT ?ThematicPath (GROUP_CONCAT(distinct concat(?ThematicPathTitle,' (',lang(?ThematicPathTitle), ')') ;separator=" | ") as ?GroupedTitles)
     (GROUP_CONCAT( distinct ?Agent;separator=" | ") as ?GAgentURI) (GROUP_CONCAT( distinct ?AgentName;separator=" | ") as ?GAgentName)
WHERE {  
  ?ThematicPath rdf:type ctp:ThematicPath.  
  ?ThematicPath ctp:hasRelationToAgent ?RelationToAgent.  
  ?RelationToAgent ctp:hasRole ?Role.  
  FILTER(?Role = <http://vocab.getty.edu/aat/300386174>)
  ?RelationToAgent ctp:involves ?Agent.  
  OPTIONAL { ?ThematicPath ctp:hasTitle ?ThematicPathTitle}.   
  OPTIONAL { ?Agent ctp:hasName ?AgentName}.
  }  
  Group by ?ThematicPath 
LIMIT 100  