# CQ11
# Which thematic paths have been funded by the same agent?  
# Quali percorsi tematici sono stati finanziati dallo stesso agente?  

PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPath ?Agent ?Role  
WHERE{  
  ?ThematicPath ctp:hasRelationToAgent ?RelationToAgent.  
  ?RelationToAgent ctp:hasRole ?Role FILTER regex(?Role, "funder", "i").  
  ?RelationToAgent ctp:involves ?Agent.  
}  
LIMIT 10  

