# CQ13
# Which thematic paths can be identified through the subject "XYZ"?  
# Quali percorsi tematici sono individuabili attraverso il soggetto "XYZ"? 

# PS. Replace the subject to be searched in row 13, column 25 (e.g. Energy) and choose the language (after @)

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT ?SubjectLabel ?ThematicPathTitle  
WHERE{  
  ?ThematicPath ctp:hasSubject ?Subject. 
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle} .  
  Optional{ ?Subject rdfs:label ?SubjectLabel} .   
FILTER(?SubjectLabel = "Energy"@en).
}  
LIMIT 100  