# CQ15
# Which cultural, ethical and social values does the thematic path X want to convey?  
# Quali valori culturali, etici e sociali vuole trasmettere il percorso tematico X?  

# PS. Replace the ThematicPathTitle to be searched in row 12, column 33, and choose the language (after @)

PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPathTitle ?rdfs  
WHERE{  
  ?ThematicPath ctp:conveys ?rdfs.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle} .
  #FILTER(?ThematicPathTitle = "X"@lang).
}  
LIMIT 100
  