# CQ18
# The thematic path X is composed by one or more sub-thematic paths (i.e. exhibitions' sub-paths)?  
# Il percorso tematico X è composto da uno o più sotto percorsi tematici (per esempio sottofiloni tematici di una mostra)?  

# PS. Replace the ThematicPathTitle to be searched in row 15, column 33, and choose the language (after @)

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
SELECT ?ThematicPathTitle ?SubThematicPathTitle
WHERE{  
  ?ThematicPath rdf:type ctp:ThematicPath .
  ?ThematicPath ctp:includes ?SubThematicPath.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle} .
  Optional{ ?SubThematicPath ctp:hasTitle ?SubThematicPathTitle} .
  #FILTER(?ThematicPathTitle = "X"@lang).
}  
LIMIT 100  