# CQ20
# Where can cultural resources related to the thematic path X be viewed?
# Dove sono visualizzabili gli oggetti legati al percorso tematico X?  

# P.S. Replace the ThematicPathTitle to be searched in row 15, column 21.

PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPathTitle ?CulturalResourceTitle ?Link  
WHERE{  
  ?CulturalResource ctp:isPartOf ?ThematicPath.  
  ?CulturalResource ctp:linkToResource ?Link.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  Optional{ ?CulturalResource ctp:hasTitle ?CulturalResourceTitle}.  
  #?ThematicPath ctp:hasTitle ?p.  
  #FILTER(REGEX(?p, "InsertThematicPathTitleHere", "i")).   
}  
LIMIT 100  