# CQ22
# Where is it possible to buy products related to the thematic path X?  
# Dove è possibile acquistare prodotti relativi al percorso tematico X?  

# PS. Replace the ThematicPathTitle to be searched in row 18, column 33, and choose the language (after @)

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?ThematicPathTitle ?ProductTitle ?ProductType ?Link  
WHERE{  
  ?ThematicPath ctp:allowsTheSaleOf ?Product.  
  ?Product ctp:isSelledBy ?Link.  
  ?Product ctp:hasTitle ?rdfs.  
  ?Product ctp:hasType ?Type.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle} .
  Optional{ ?Product ctp:hasTitle ?ProductTitle} . 
  Optional{ ?Type rdfs:label ?ProductType} .  
  #FILTER(?ThematicPathTitle = "X"@lang).  
}  
LIMIT 10  