# CQ25
# Which thematic routes have been created in the year YYYY?  
# Quali percorsi tematici sono stati creati nell'anno YYYY?  

# example with year 2024

PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPathTitle ?Date  
WHERE{  
  ?ThematicPath ctp:hasCreationDate ?Date.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  FILTER (?Date >= "2024-01-01"^^<http://www.w3.org/2001/XMLSchema#date> && ?Date <="2024-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)  
}  
LIMIT 100  