# CQ3
# Where are cultural objects connected to thematic route X usually kept?  
# Dove sono solitamente conservati gli oggetti culturali connessi al percorso tematico X?  

# PS. Replace the ThematicPathTitle to be searched in row 27, column 32, and choose the language after @.

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT ?ThematicPathTitle ?CulturalResourceTitle ?PlaceName  
WHERE{  
  {  
    ?ThematicPath ctp:hasPart ?CulturalResource.  
  }  
  UNION  
  {  
    ?ThematicPath ctp:hasSlot ?OrderedListSlot.  
    ?OrderedListSlot ctp:hasItem ?CulturalResource.  
  }  
  ?CulturalResource ctp:isPreservedBy ?RelationToAgent.  
  ?RelationToAgent ctp:hasRole ?Role.  
  ?Role rdfs:label ?Holder.  
  ?RelationToAgent ctp:involves ?Agent.  
  ?Agent ctp:hasPlace ?Place.  
  Optional{?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  Optional{?CulturalResource ctp:hasTitle ?CulturalResourceTitle}.  
  Optional{?Place ctp:hasTitle ?PlaceName}.  
  FILTER(?ThematicPathTitle = "InsertTitleHere"@LANG).  
}  
GROUP BY ?ThematicPathTitle ?CulturalResourceTitle ?PlaceName  
LIMIT 100  