# CQ4
# To which historical period does thematic path X refer?  
# A quale periodo storico fa riferimento il percorso tematico X?  

# P.S. Replace the ThematicPathTitle to be searched in row 16, column 21.

PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT ?ThematicPathTitle ?TemporalEntityLabel  
WHERE{  
  ?ThematicPath ctp:refersToTemporalEntity ?TemporalEntity.  
  Optional{?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  Optional{ ?TemporalEntity rdfs:label ?TemporalEntityLabel}.  
  BIND(LANG(?ThematicPathTitle) as ?lang).
  #?ThematicPath ctp:hasTitle ?p.  
  #FILTER(REGEX(?p, "InsertThematicPathTitleHere", "i")).  
  FILTER(LANGMATCHES(LANG(?ThematicPathTitle), ?lang) &&  
         LANGMATCHES(LANG(?TemporalEntityLabel), ?lang))
}  
LIMIT 100  

