PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPath ?CulturalResource ?Agent  
WHERE{  
{ ?ThematicPath ctp:hasPart ?CulturalResource.  
  ?CulturalResource ctp:hasRelationToAgent ?RelationToAgent.  
  ?RelationToAgent ctp:hasRole ?Role FILTER regex(?Role, "creator", "i").  
  ?RelationToAgent ctp:involves ?Agent.}  

UNION  

{ ?ThematicPath ctp:hasPart ?CulturalResource.  
  ?CulturalResource ctp:hasTime ?TemporalEntity.}  
}  
LIMIT 10  