# CQ15
# Which cultural, ethical, and social values does the thematic path X aim to convey?  
# Quali valori culturali, etici e sociali vuole trasmettere il percorso tematico X?  

# P.S. Replace the ThematicPathTitle to be searched in row 13, column 21.

PREFIX ctp: <https://w3id.org/ctp#>  
SELECT ?ThematicPathTitle ?Message  
WHERE{  
  ?ThematicPath ctp:conveys ?Message.  
  Optional{ ?ThematicPath ctp:hasTitle ?ThematicPathTitle}.  
  #?ThematicPath ctp:hasTitle ?p.  
  #FILTER(REGEX(?p, "InsertThematicPathTitleHere", "i")).  
  BIND(LANG(?ThematicPathTitle) as ?lang).
  FILTER(LANGMATCHES(LANG(?ThematicPathTitle), ?lang) &&  
         LANGMATCHES(LANG(?Message), ?lang))
}  
LIMIT 100  