PREFIX ctp: <https://w3id.org/ctp#>  
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
SELECT * 
WHERE{  
  ?ThematicPath ctp:hasTheme ?Theme.  
  Optional{ ?ThematicPath rdfs:label ?ThematicPathLabel} . 
  Optional{ ?Theme rdfs:label ?Theme} . 
}  
LIMIT 10  